kind: Template
apiVersion: v1
metadata:
  name: build-wordpress-core
  annotations:
    openshift.io/display-name: wordpress-core-php-fpm
    description: Build templates for the WordPress Image.
    tags: php-fpm,wordpress

parameters:
  - name: APP_NAME
    displayName: "App Name"
    description: "The name of the application (grouped)."
    required: true
    value: "wordpress"
  - name: GIT_URL
    displayName: "GIT Source Repo URL"
    description: "A GIT URL to your source code."
    required: true
    value: "https://github.com/bcgov/wordpress.git"
  - name: GIT_REF
    displayName: "Git Reference"
    description: "The git reference or branch."
    required: true
    value: "main"
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "e49a54"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "tools"
  - name: IMAGE_TAG
    displayName: "Output Image Tag"
    description: "The tag given to the built image."
    required: true
    value: "latest"
  - name: ROLE_NAME
    displayName: "Component Name"
    description: "The name of the application role."
    required: true
    value: "wordpress-run"

  - name: RUNTIMEIMAGE_NAME
    displayName: "Source Image Name"
    description: "The image to use as the Runtime Image."
    value: "php74-fpm-base"
  - name: RUNTIMEIMAGE_TAG
    displayName: "Source Image Tag"
    description: "The s2i image tag which is used to run the code."
    value: "dev"

  - name: SOURCE_CONTEXT_DIR
    displayName: "Source Context Directory"
    description: "The source context directory."
    required: false
    value: "openshift/templates/images/wordpress/docker"

objects:
  # Image stream for the runtime image.
  # Image stream for the built base image.
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: Keeps track of base WordPress core images
      labels:
        name: ${APP_NAME}-${ROLE_NAME}-images
        env: ${ENV_NAME}
    spec:
      lookupPolicy:
        local: true
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}
      labels:
        name: ${APP_NAME}-${ROLE_NAME}
        env: ${ENV_NAME}
    spec:
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2
      runPolicy: Parallel
      completionDeadlineSeconds: 1800
      source:
        type: Git
        git:
          ref: ${GIT_REF}
          uri: ${GIT_URL}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Docker
      triggers:
        - type: ConfigChange
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}-${ROLE_NAME}:${IMAGE_TAG}
      resources: { }
      postCommit: { }

