kind: Template
apiVersion: v1
metadata:
  name: build-wordpress-nginx
  annotations:
    openshift.io/display-name: wordpress-nginx
    description: Build templates for the nginx web server of the WordPress deploy.
    tags: nginx,wordpress

parameters:

  - name: APP_NAME
    displayName: "App Name"
    description: "The name of the application (grouped)."
    required: true
    value: "wordpress"
  - name: GIT_URL
    displayName: "GIT Source Repo URL"
    description: "A GIT URL to your source code."
    required: true
    value: "https://github.com/bcgov/wordpress.git"
  - name: GIT_REF
    displayName: "Git Reference"
    description: "The git reference or branch."
    required: true
    value: "main"
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "e49a54"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "tools"
  - name: IMAGE_TAG
    displayName: "Output Image Tag"
    description: "The tag given to the built image."
    required: true
    value: "latest"
  - name: ROLE_NAME
    displayName: "Name"
    description: "Name of the image."
    required: true
    value: "nginx-run"
  - name: SOURCE_CONTEXT_DIR
    displayName: "Source Context Directory"
    description: "The source context directory."
    required: false
    value: "openshift/templates/images/nginx/docker"
  
objects:
  # Image stream for the built base image.
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: Keeps track of ${APP_NAME}-${ROLE_NAME} images
      labels:
        name: ${APP_NAME}-${ROLE_NAME}-images
        env: ${ENV_NAME}
        app: ${APP_NAME}
        role: ${ROLE_NAME}
        source: dockerhub

  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}
      labels:
        name: ${APP_NAME}-${ROLE_NAME}
        env: ${ENV_NAME}
    spec:
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2
      runPolicy: Serial
      source:
        type: Git
        git:
          ref: ${GIT_REF}
          uri: ${GIT_URL}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Docker
        dockerStrategy:
          forcePull: true
      triggers:
        - type: ConfigChange
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}-${ROLE_NAME}:${IMAGE_TAG}
      resources: { }
      postCommit: { }
